name: Deploy API

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'api/**'

jobs:
  deploy:
    runs-on: [self-hosted, deploy]
    environment: production

    steps:
      - uses: actions/checkout@v4
      - name: copy repository
        uses: appleboy/scp-action@v1
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "api/*"
          target: /opt/grit/zabmap/api
          strip_components: 1
          rm: true
      - name: install dependencies
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/grit/zabmap/api
            /gritadm/.local/bin/uv sync
      - name: restart the service
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart zabmap.service
